require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Events::EventsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Events::Event. As you add validations to Events::Event, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Events::EventsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all events_events as @events_events" do
      event = Events::Event.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:events_events)).to eq([event])
    end
  end

  describe "GET show" do
    it "assigns the requested events_event as @events_event" do
      event = Events::Event.create! valid_attributes
      get :show, {:id => event.to_param}, valid_session
      expect(assigns(:events_event)).to eq(event)
    end
  end

  describe "GET new" do
    it "assigns a new events_event as @events_event" do
      get :new, {}, valid_session
      expect(assigns(:events_event)).to be_a_new(Events::Event)
    end
  end

  describe "GET edit" do
    it "assigns the requested events_event as @events_event" do
      event = Events::Event.create! valid_attributes
      get :edit, {:id => event.to_param}, valid_session
      expect(assigns(:events_event)).to eq(event)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Events::Event" do
        expect {
          post :create, {:events_event => valid_attributes}, valid_session
        }.to change(Events::Event, :count).by(1)
      end

      it "assigns a newly created events_event as @events_event" do
        post :create, {:events_event => valid_attributes}, valid_session
        expect(assigns(:events_event)).to be_a(Events::Event)
        expect(assigns(:events_event)).to be_persisted
      end

      it "redirects to the created events_event" do
        post :create, {:events_event => valid_attributes}, valid_session
        expect(response).to redirect_to(Events::Event.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved events_event as @events_event" do
        post :create, {:events_event => invalid_attributes}, valid_session
        expect(assigns(:events_event)).to be_a_new(Events::Event)
      end

      it "re-renders the 'new' template" do
        post :create, {:events_event => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested events_event" do
        event = Events::Event.create! valid_attributes
        put :update, {:id => event.to_param, :events_event => new_attributes}, valid_session
        event.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested events_event as @events_event" do
        event = Events::Event.create! valid_attributes
        put :update, {:id => event.to_param, :events_event => valid_attributes}, valid_session
        expect(assigns(:events_event)).to eq(event)
      end

      it "redirects to the events_event" do
        event = Events::Event.create! valid_attributes
        put :update, {:id => event.to_param, :events_event => valid_attributes}, valid_session
        expect(response).to redirect_to(event)
      end
    end

    describe "with invalid params" do
      it "assigns the events_event as @events_event" do
        event = Events::Event.create! valid_attributes
        put :update, {:id => event.to_param, :events_event => invalid_attributes}, valid_session
        expect(assigns(:events_event)).to eq(event)
      end

      it "re-renders the 'edit' template" do
        event = Events::Event.create! valid_attributes
        put :update, {:id => event.to_param, :events_event => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested events_event" do
      event = Events::Event.create! valid_attributes
      expect {
        delete :destroy, {:id => event.to_param}, valid_session
      }.to change(Events::Event, :count).by(-1)
    end

    it "redirects to the events_events list" do
      event = Events::Event.create! valid_attributes
      delete :destroy, {:id => event.to_param}, valid_session
      expect(response).to redirect_to(events_events_url)
    end
  end

end
